### ISSUE TITLE
Alternative:  Acrobat - [LibreOffice Draw]

### ISSUE THREAD

**Issue by Gurbuzguven** [eaaasun/adobe-sucks-scrotum#23]
### Adobe App

Acrobat

### Alternative App

LibreOffice Draw

### Alternative App Link

https://www.libreoffice.org/

### Alternative App Pricing

Free

### Open Source

Yes

### Reason

Can edit pdf documents(not just annotate, edit text inside pdfs), however only works well with text based pdfs.

**Comment by eaaasun** [comment]
Libreoffice draw was not made for PDF work, and is quite limited when doing so. I don't think it's a suitable alternative to Acrobat, but thank you for contributing!

**Comment by Gurbuzguven** [comment]
Thanks for explanation and great work!
