### ISSUE TITLE
Alternative: Nuke

### ISSUE THREAD

**Issue by HenryMorgans** [eaaasun/adobe-sucks-scrotum#44]
### Website-Generated Content

---
title: Nuke
description: INCREDIBLY POWERFUL FOR VISUAL EFFECTS, NOT SUITABLE FOR ANIMATION
pricing:
 - paid
adobeApps:
 - After Effects
link: https://www.foundry.com/products/nuke-family/nuke
---

**Comment by eaaasun** [comment]
There is a free non-commercial option, i'll add that too
